user API
woowa-techcamp-2020/bmart-8 pull request #124
Opened 2020-08-26 12:26 UTC by hanSong2

## 설명
토큰을 기반으로, 유저 정보를 불러오거나 프로필을 업데이트 할 수 있습니다.
유저 전체 목록이나 아이디를 인자로 주는건 관리자가 생기면 구현 예정.....

## 관련 이슈
- resolved #53 

## 기타(스크린샷 등)

2020-08-26 15:59 UTC, nohgijin approved these changes

2020-08-26 16:14 UTC, atobaum commented on server/src/graphql/types/user.graphql
> +type UserProfile {
유저 프로필 따로 뺀거 더 보기 좋네요.

2020-08-26 16:16 UTC, atobaum requested changes

2020-08-26 16:16 UTC, atobaum commented on server/src/graphql/types/user.graphql
> +  id: ID!
User.id하고 UserProfile.id를 클라이언트에서 어디에 사용하나요?

2020-08-26 16:16 UTC, atobaum commented on server/src/graphql/resolvers/user.ts
> -    currentUser: (parent: any, args: any, { prisma, user }: any) => {
클라이언트 useUser에서 이 쿼리를 사용하고 있어요. useUser도 고쳐야합니다.

2020-08-27 11:08 UTC, hanSong2 commented on server/src/graphql/resolvers/user.ts
> -    currentUser: (parent: any, args: any, { prisma, user }: any) => {
해쥬

2020-08-28 02:59 UTC, atobaum approved these changes

2020-08-28 03:01 UTC, merged